spring.application.name=SpringSecEx

#spring.security.user.name=juandavyc
#spring.security.user.password= secret


spring.datasource.url=jdbc:postgresql://localhost:5432/juandavyc1
spring.datasource.username=juandavyc
spring.datasource.password=secret


