spring.application.name=SpringSecEx


spring.datasource.url=jdbc:postgresql://localhost:5432/juandavyc1
spring.datasource.username=juandavyc
spring.datasource.password=secret

spring.jpa.show-sql=true


